"""Read SolidWorks propeller configurations and assembly references.

This closes the possibility that one SLDPRT encodes normal/reverse blades as
different configurations even though every assembly component uses one path.
The operation is read-only and exits SolidWorks when finished.
"""

from __future__ import annotations

import json
from pathlib import Path

import pythoncom
import win32com.client


SW_DOC_ASSEMBLY = 2
SW_OPEN_SILENT = 1
SW_OPEN_READ_ONLY = 2


def call_or_value(obj, name):
    value = getattr(obj, name)
    return value() if callable(value) else value


def inspect(assembly: Path, output: Path) -> dict:
    # Dynamic DispatchEx avoids depending on a locally generated makepy cache;
    # some SolidWorks installations expose automation correctly while their
    # registered type library cannot be regenerated by newer Python versions.
    app = win32com.client.DispatchEx("SldWorks.Application")
    app.Visible = False
    app.CommandInProgress = True
    errors = win32com.client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)
    warnings = win32com.client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)
    document = None
    try:
        document = app.OpenDoc6(
            str(assembly.resolve()),
            SW_DOC_ASSEMBLY,
            SW_OPEN_SILENT | SW_OPEN_READ_ONLY,
            "",
            errors,
            warnings,
        )
        if document is None:
            raise RuntimeError(f"OpenDoc6 failed: {errors.value}/{warnings.value}")
        document.ResolveAllLightWeightComponents(False)
        instances = []
        configuration_names: set[str] = set()
        design_table_present = None
        source_part = None
        for component in document.GetComponents(False) or []:
            path = str(call_or_value(component, "GetPathName") or "")
            if Path(path).name.casefold() != "f螺旋桨.sldprt":
                continue
            # In late-bound SolidWorks COM, GetModelDoc2 is exposed as a
            # dispatch property even though the typed API documents a method.
            model = component.GetModelDoc2
            referenced = str(call_or_value(component, "ReferencedConfiguration"))
            instances.append(
                {
                    "instance": str(call_or_value(component, "Name2")),
                    "source_part": path,
                    "referenced_configuration": referenced,
                }
            )
            source_part = path
            if model is not None:
                configuration_names.update(
                    str(value)
                    for value in (call_or_value(model, "GetConfigurationNames") or [])
                )
                if design_table_present is None:
                    try:
                        design_table_present = call_or_value(model, "GetDesignTable") is not None
                    except Exception:
                        design_table_present = "API_UNAVAILABLE"
        result = {
            "schema": 1,
            "source_assembly": str(assembly.resolve()),
            "source_part": source_part,
            "configuration_names": sorted(configuration_names),
            "configuration_count": len(configuration_names),
            "design_table_present": design_table_present,
            "instances": sorted(instances, key=lambda row: row["instance"]),
        }
        result["conclusion"] = (
            "MULTIPLE_CONFIGURATIONS_REQUIRE_REVIEW"
            if len(configuration_names) > 1
            or len({row["referenced_configuration"] for row in instances}) > 1
            else "SINGLE_CONFIGURATION_NO_HIDDEN_HANDEDNESS"
        )
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(
            json.dumps(result, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        return result
    finally:
        if document is not None:
            app.CloseDoc(call_or_value(document, "GetTitle"))
        app.CommandInProgress = False
        app.ExitApp()


if __name__ == "__main__":
    project = Path(__file__).resolve().parents[4]
    result = inspect(
        project / "零件" / "完整零件" / "组合无人机.SLDASM",
        project
        / "drone_sim_ws"
        / "analysis"
        / "cad_direct"
        / "propeller_configuration_evidence.json",
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
